# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - name: Installing pre-requisites
    init: sudo apt-get install -y ant
    command: ant compile


# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart

vscode:
    extensions:
        - svelte.svelte-vscode
        - prettier
